### ISSUE TITLE
bug: Dart SDK not making network calls

### ISSUE THREAD

**Issue by isaaclindenman** [basemind-ai/sdk-dart#5]
When making network calls in a Flutter app, there is an error in the browser console.
I tried rendering the app on Chrome and running it and got the error in the console.

![Image](https://github.com/basemind-ai/sdk-dart/assets/30323315/8367ed78-7795-418c-9c5d-fb34f791fe85)

 

![Image](https://github.com/basemind-ai/sdk-dart/assets/30323315/744ad44b-5521-4ddc-b10b-3cebcc01fad4)

**Comment by Goldziher** [comment]
We do not support web ATM. Try using mobile.

**Comment by Goldziher** [comment]
SDK is working fine
